name: Custom Build

on:
  workflow_dispatch:
    inputs:
      board_type:
        description: 'ESP32 Board Type'
        required: true
        type: choice
        options:
          - esp32
          - esp32s2
          - esp32s3
          - esp32c3
          - esp32c6
        default: 'esp32s2'
      display_type:
        description: 'Display Configuration'
        required: true
        type: choice
        options:
          - custom
          - none
          - MarauderV4_FlipperHub
          - MarauderV6_AwokDual
          - AwokMini
          - ESP32-S3-Cardputer
          - LillyGoTWatch_S3
          - CYD2USB
          - CYDMicroUSB
          - CYDDualUSB
          - CYD2USB2.4_Inch
          - Waveshare_LCD
          - Crowtech_LCD
        default: 'none'
      screen_width:
        description: 'Screen Width (only for custom display)'
        required: false
        type: string
      screen_height:
        description: 'Screen Height (only for custom display)'
        required: false
        type: string
      use_touch:
        description: 'Enable Touch Support (auto-enabled for some displays)'
        required: true
        type: boolean
        default: false
      flash_size:
        description: 'Flash Size'
        required: true
        type: choice
        options:
          - 4MB
        default: '4MB'

jobs:
  build:
    name: Build Custom Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Configuration
        run: |
          # Board-Display Compatibility Check
          case "${{ github.event.inputs.display_type }}" in
            "MarauderV4_FlipperHub"|"MarauderV6_AwokDual"|"AwokMini"|"CYD2USB"|"CYDMicroUSB"|"CYDDualUSB"|"CYD2USB2.4_Inch")
              if [ "${{ github.event.inputs.board_type }}" != "esp32" ] && [ "${{ github.event.inputs.board_type }}" != "esp32s2" ]; then
                echo "Error: ${{ github.event.inputs.display_type }} requires ESP32 or ESP32-S2 board type"
                exit 1
              fi
              ;;
          esac

          # Flash Size Validation
          case "${{ github.event.inputs.display_type }}" in
            "Waveshare_LCD"|"Crowtech_LCD")
              if [ "${{ github.event.inputs.flash_size }}" == "4MB" ]; then
                echo "::warning::7-inch displays are recommended to use 8MB or larger flash size"
              fi
              ;;
          esac

          # Custom Display Validation
          if [ "${{ github.event.inputs.display_type }}" == "custom" ]; then
            if [ -z "${{ github.event.inputs.screen_width }}" ] || [ -z "${{ github.event.inputs.screen_height }}" ]; then
              echo "Error: Screen width and height are required for custom display configuration"
              exit 1
            fi
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ESP-IDF
        run: |
          sudo apt-get update
          sudo apt-get install -y wget git flex bison gperf python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util
          git clone -b v5.3.1 --depth 1 https://github.com/espressif/esp-idf.git ~/esp-idf
          ~/esp-idf/install.sh

      - name: Generate Custom SDK Config
        run: |
          if [ "${{ github.event.inputs.display_type }}" != "custom" ] && [ "${{ github.event.inputs.display_type }}" != "none" ]; then
            case "${{ github.event.inputs.display_type }}" in
              "MarauderV4_FlipperHub")
                cp "configs/sdkconfig.marauderv4" sdkconfig.defaults
                ;;
              "MarauderV6_AwokDual")
                cp "configs/sdkconfig.marauderv6" sdkconfig.defaults
              
